version: '3.8'


services:
  scraper:
   build: .
   volumes:
     - "./src:/app"
     - "./proxylist2.csv:/app/proxylist.csv"
   environment:
     - MONGODB_HOST=${MONGO_HOST}
     - MONGODB_DATABASE=${MONGODB_DATABASE}
     - LOG_LEVEL=${LOG_LEVEL}
     - NUM_SCRAPING_WORKERS=2
   entrypoint: "python app.py"
   ports:
     - 8084:5000
   depends_on:
     - db

  db:
    image: mongo:${MONGO_VERSION}
    ports:
      - 27017:27017
