version: '3.8'


services:
  scraper:
   build: .
   volumes:
     - "./src:/app"
   environment:
     - MONGO_HOST=${MONGO_HOST}
     - MONGO_DB=${MONGO_DB}
     - LOG_LEVEL=${LOG_LEVEL}
   ports:
     - 8084:5000
   depends_on:
     - db

  db:
    image: mongo:${MONGO_VERSION}
    ports:
      - 27017:27017
