version: '3.8'


services:
  scraper:
   build: .
   volumes:
     - "./src:/app"
   environment:
     - MONGO_HOST=${MONGO_HOST}
     - MONGO_DB=${MONGO_DB}
     - LOG_LEVEL=${LOG_LEVEL}
   tty: true
   stdin_open: true
   entrypoint: bash
   depends_on:
     - db
  
  db:
    image: mongo:${MONGO_VERSION}
